### ISSUE TITLE
Full stars option

### ISSUE THREAD

**Issue by herzzanu** [vevix/ember-star-rating#1]
Is there any way to always have full stars and disable half empty stars?

**Comment by vevix** [comment]
Not at this time as this was built for our specific needs, I'd be happy to accept a PR though! Eventually I plan to get around to this again and clean it up.

You may want to take a look at https://github.com/vevix/ember-star-rateyo which is wrapper around  the jQuery library [RateYo!](http://rateyo.fundoocode.ninja/) -- That'll allow you much more customization.
